<?php
/**
 * Title: Header template.
 *
 * Description: Defines header content.
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="ie ie6 lte9 lte8 lte7" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 7]>
<html class="ie ie7 lte9 lte8 lte7" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8 lte9 lte8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 9]>
<html class="ie ie9" <?php language_attributes(); ?>> 
<![endif]-->
<!--[if gt IE 9]>  <html <?php language_attributes(); ?>> <![endif]-->
<!--[if !IE]><!--> 
<html <?php language_attributes(); ?>>
<!--<![endif]-->
<head>
	<meta charset="<?php bloginfo( 'charset' ); ?>" />
	<meta name="viewport" content="initial-scale=1.0; maximum-scale=3.0; width=device-width" />
	
	<link rel="profile" href="http://gmpg.org/xfn/11" />
	<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>" />
	
	<!-- IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
		<script src="<?php echo get_template_directory_uri(); ?>/inc/js/html5.js" type="text/javascript"></script>
	<![endif]-->
	
	<?php wp_head(); ?>

</head>

<body <?php body_class(); ?>>

<div class="full-width-container header-full-width">

<?php $header_image = get_theme_mod( 'header_image', get_template_directory_uri() . '/images/header.jpg' );
      $header_image = ( $header_image != '' ) ? $header_image : get_template_directory_uri() . '/images/header.jpg'; ?>

	

<div class="header-container header-image" style="background-image: url('<?php echo esc_url( $header_image );?>'); background-size: 100% 100%; background-repeat: no-repeat;">

	
  <div class="container" >
    
  <?php do_action('cyberchimps_before_wrapper'); ?>
  
    <div class="container-fluid">
    
      <div id="header_nav_container">
      
        <div class="row-fluid">
        
			<div class="span3">
				<?php do_action( 'cyberchimps_header' ); ?>
          </div><!-- span3 -->
          <div class="span2">

			  <?php cyberchimps_header_social_icons(); ?>

                      <a data-target='.collapse-icon' data-toggle='collapse' class='icontoggle'><b class="caret1"></b></a>

		  </div>

          <div class="span7">
			  <?php do_action('cyberchimps_before_navigation'); ?>
          
            	<nav id="navigation" class="row-fluid" role="navigation">

              <div class="main-navigation navbar">

                <div class="navbar-inner">

                  <div class="container">
                  <?php /* hide collapsing menu if not responsive */
                  if( get_theme_mod( 'responsive_design', 'checked' ) ): ?>
		 <div class="nav-collapse collapse">
                    <?php endif; ?>
                    
		<?php wp_nav_menu( array( 'theme_location'  => 'primary', 'menu_class' => 'nav', 'walker' => new cyberchimps_Walker(), 'fallback_cb' => 'cyberchimps_fallback_menu' ) ); ?>

                    <?php /* hide collapsing menu if not responsive */
                    if( get_theme_mod( 'responsive_design', 'checked' ) ): ?>
                    </div><!-- collapse -->
                  
                  <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

                  <span class="icon-bar"></span>

                  <span class="icon-bar"></span>

                  <span class="icon-bar"></span>

                  </a>
				  
                  <?php endif; ?>
                  </div><!-- container -->
		</div><!-- .navbar-inner .row-fluid -->

              </div><!-- main-navigation navbar -->
            </nav><!-- #navigation -->

          <?php do_action('cyberchimps_after_navigation'); ?>
          </div><!-- span9 -->
        </div><!-- row fluid -->
      </div><!-- header nav container -->
      
    </div><!-- container-fluid -->
  </div><!-- container -->
  <div class="header-image-featured">
	  <div class="container">
		  <div class="container-fluid">
			  <div id="header-featured-content">
				  <?php
			
					  $theme_options_main = get_option('theme_mods_'.get_template());
					  if(!isset($theme_options_main['header_featured_title']))
					  {
					  	set_theme_mod('header_featured_title', 'Beautiful WordPress Themes');
					  }
					  if(!isset($theme_options_main['header_featured_text']))
					  {
					  	set_theme_mod('header_featured_text', 'Create a great website in minutes using CyberChimps theme');
					  }
					  if(!isset($theme_options_main['header_featured_link']))
					  {
					  	set_theme_mod('header_featured_link', '#');
					  }
					  if(!isset($theme_options_main['header_featured_link_text']))
					  {
					  	set_theme_mod('header_featured_link_text', 'View Theme & Pricing');
					  }
				  
						$header_title = get_theme_mod( 'header_featured_title' );
						$header_text = get_theme_mod( 'header_featured_text' );
						$header_link = get_theme_mod( 'header_featured_link' ) ? get_theme_mod( 'header_featured_link' ) : '#';
						$header_link_text = get_theme_mod( 'header_featured_link_text' );
					
				 
				  ?>
				  <?php if ( ! empty( $header_title ) ) { ?>
							<h3 class="header-content-title"><?php echo $header_title; ?></h3>
				  <?php } ?>
				  <?php if ( ! empty( $header_text ) ) { ?>
							<div class="header-content-text"><?php echo $header_text; ?></div>
				  <?php } ?>
				  <?php if ( ! empty( $header_link_text ) ) { ?>
							<div class="header-content-link">
								  <a href="<?php echo $header_link; ?>" title="<?php echo $header_link_text; ?>">
									  <?php echo $header_link_text; ?>
								  </a>
							</div>
				  <?php } ?>
			  </div>
		  </div>
	  </div>
  </div>
</div><!-- header container -->
</div><!--container full width -->
<div class="container">
<div id="wrapper" class="container-fluid">
